- name: Create a virtual machine on given ESXi hostname
  vmware_guest:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    folder: "{{ folder }}"
    name: "{{ item.value.vcenter.vm_name }}"
    state: poweredon
    guest_id: "{{ item.value.vcenter.guest_id }}"
    esxi_hostname: "{{ item.value.esxi.hostname }}"
    datacenter: "{{ item.value.datacenter }}"
    cdrom:
      type: iso
      iso_path: "{{ item.value.cdrom.iso_path }}"
      controller_type: "{{ item.value.cdrom.controller_type }}"
      controller_number: "{{ item.value.cdrom.controller_number }}"
      unit_number: "{{ item.value.cdrom.unit_number }}"
    disk:
      - size_gb: "{{ item.value.disk.size_gb }}"
        type: "{{ item.value.disk.type }}"
        datastore: "{{ item.value.disk.datastore }}"
    hardware:
      memory_mb: "{{ item.value.hardware.memory_mb }}"
      num_cpus: "{{ item.value.hardware.num_cpus }}"
      scsi: "{{ item.value.hardware.scsi }}"
    networks:
      - name: "{{ item.value.networks.name }}"
        # mac: "{{ item.value.networks.mac }}"
        # ip: "{{ item.value.networks.ip }}"
        # netmask: "{{ item.value.networks.netmask }}"
        device_type: "{{ item.value.networks.device_type }}"
    # wait_for_ip_address: yes
  register: result
  loop: "{{ q('dict', instances) }}"

- name: DEBUG print result
  debug: var=result
