# ansible_python_interpreter: /usr/bin/python3
hostname: "sample.com"
username: "shanpu"
password: "***"
folder: "/DC1/vm/"

instances:
  test1:
    vcenter:
      vm_name: "sample-vm"
      guest_id: "ubuntu64Guest" # refer https://code.vmware.com/apis/358/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html
    esxi:
      hostname: "sample" # This is hostname of particular ESXi server on which user wants VM to be deployed
    datacenter: "sample_datacenter"
    cdrom:
      iso_path: "[datastore1] path/to/file.iso"
      controller_type: sata
      controller_number: 0
      unit_number: 0
    disk:
      size_gb: 32
      type: thin
      datastore: "sample"
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: lsilogic
    networks:
      name: "sample_network"
      device_type: vmxnet3
  test2:
    vcenter:
      vm_name: "sample-vm"
      guest_id: "ubuntu64Guest" # refer https://code.vmware.com/apis/358/doc/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html
    esxi:
      hostname: "sample" # This is hostname of particular ESXi server on which user wants VM to be deployed
    datacenter: "sample_datacenter"
    cdrom:
      iso_path: "[datastore1] path/to/file.iso"
      controller_type: sata
      controller_number: 0
      unit_number: 0
    disk:
      size_gb: 32
      type: thin
      datastore: "sample"
    hardware:
      memory_mb: 4096
      num_cpus: 2
      scsi: lsilogic
    networks:
      name: "sample_network"
      device_type: vmxnet3